PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE teams (teamid INTEGER PRIMARY KEY, teamname);
INSERT INTO "teams" VALUES(1,'A');
INSERT INTO "teams" VALUES(2,'B');
INSERT INTO "teams" VALUES(3,'C');
INSERT INTO "teams" VALUES(4,'D');
INSERT INTO "teams" VALUES(5,'E');
INSERT INTO "teams" VALUES(6,'F');
CREATE TABLE cup (teamid INTEGER, week INTEGER, distance REAL, PRIMARY KEY(teamid, week));
CREATE TABLE playoff (teamid INTEGER, bracket INTEGER, wins INTEGER DEFAULT 0);
CREATE TABLE points (teamid INTEGER, week INTEGER, points INTEGER, sumpoints INTEGER, PRIMARY KEY(teamid, week));
CREATE TABLE runners (runnerid INTEGER PRIMARY KEY, runnername, teamid INTEGER, goal REAL);
CREATE TABLE log (runid INTEGER PRIMARY KEY, runnerid INTEGER, date, distance REAL, time, type);
CREATE TABLE wlog (runnerid INTEGER, week INTEGER, distance REAL, PRIMARY KEY(runnerid, week));
COMMIT;
